https://rdapi.aayulogic.io/api/v1/auth/generate-otp/
https://rdapi.aayulogic.io/api/v1/auth/get-token/
https://rdapi.aayulogic.io/api/v1/auth/manager-login/
https://rdapi.aayulogic.io/api/v1/auth/refresh-token/
https://rdapi.aayulogic.io/api/v1/auth/verify-otp/
https://rdapi.aayulogic.io/api/v1/auth/verify-token/
https://rdapi.aayulogic.io/api/v1/blogs/
https://rdapi.aayulogic.io/api/v1/blogs/blog-category/
https://rdapi.aayulogic.io/api/v1/blogs/blog-category/{id}/
https://rdapi.aayulogic.io/api/v1/blogs/blog-tag/
https://rdapi.aayulogic.io/api/v1/blogs/blog-tag/{id}/
https://rdapi.aayulogic.io/api/v1/blogs/by-archives/
https://rdapi.aayulogic.io/api/v1/blogs/by-categories/
https://rdapi.aayulogic.io/api/v1/blogs/by-tags/
https://rdapi.aayulogic.io/api/v1/blogs/overview/
https://rdapi.aayulogic.io/api/v1/blogs/random/
https://rdapi.aayulogic.io/api/v1/blogs/stats/
https://rdapi.aayulogic.io/api/v1/blogs/{slug}/
https://rdapi.aayulogic.io/api/v1/blogs/{slug}/status-change/
https://rdapi.aayulogic.io/api/v1/business-post/
https://rdapi.aayulogic.io/api/v1/business-post/by-categories/
https://rdapi.aayulogic.io/api/v1/business-post/category/
https://rdapi.aayulogic.io/api/v1/business-post/category/{slug}/
https://rdapi.aayulogic.io/api/v1/business-post/count/
https://rdapi.aayulogic.io/api/v1/business-post/image/{id}/
https://rdapi.aayulogic.io/api/v1/business-post/overview/
https://rdapi.aayulogic.io/api/v1/business-post/stats/
https://rdapi.aayulogic.io/api/v1/business-post/tag/
https://rdapi.aayulogic.io/api/v1/business-post/tag/{id}/
https://rdapi.aayulogic.io/api/v1/business-post/{slug}/
https://rdapi.aayulogic.io/api/v1/business-post/{slug}/send-mail/
https://rdapi.aayulogic.io/api/v1/business-post/{slug}/status-change/
https://rdapi.aayulogic.io/api/v1/common/business-training-stat/
https://rdapi.aayulogic.io/api/v1/common/cities/
https://rdapi.aayulogic.io/api/v1/common/cities/{id}/
https://rdapi.aayulogic.io/api/v1/common/contact-us/
https://rdapi.aayulogic.io/api/v1/common/countries-and-currencies/
https://rdapi.aayulogic.io/api/v1/common/country/
https://rdapi.aayulogic.io/api/v1/common/country/{id}/
https://rdapi.aayulogic.io/api/v1/common/designations/
https://rdapi.aayulogic.io/api/v1/common/designations/stats/
https://rdapi.aayulogic.io/api/v1/common/designations/{id}/
https://rdapi.aayulogic.io/api/v1/common/disabilityfactor/
https://rdapi.aayulogic.io/api/v1/common/disabilityfactor/stats/
https://rdapi.aayulogic.io/api/v1/common/disabilityfactor/{id}/
https://rdapi.aayulogic.io/api/v1/common/district/
https://rdapi.aayulogic.io/api/v1/common/district/{id}/
https://rdapi.aayulogic.io/api/v1/common/document-categories/
https://rdapi.aayulogic.io/api/v1/common/document-categories/{id}/
https://rdapi.aayulogic.io/api/v1/common/education-boards/
https://rdapi.aayulogic.io/api/v1/common/education-boards/stats/
https://rdapi.aayulogic.io/api/v1/common/education-boards/{id}/
https://rdapi.aayulogic.io/api/v1/common/education-degrees/
https://rdapi.aayulogic.io/api/v1/common/education-degrees/{id}/
https://rdapi.aayulogic.io/api/v1/common/education-programs/
https://rdapi.aayulogic.io/api/v1/common/education-programs/stats/
https://rdapi.aayulogic.io/api/v1/common/education-programs/{id}/
https://rdapi.aayulogic.io/api/v1/common/gesi/
https://rdapi.aayulogic.io/api/v1/common/gesi/stats/
https://rdapi.aayulogic.io/api/v1/common/gesi/{id}/
https://rdapi.aayulogic.io/api/v1/common/industries/
https://rdapi.aayulogic.io/api/v1/common/industries/{id}/
https://rdapi.aayulogic.io/api/v1/common/institutions/
https://rdapi.aayulogic.io/api/v1/common/institutions/stats/
https://rdapi.aayulogic.io/api/v1/common/institutions/{id}/
https://rdapi.aayulogic.io/api/v1/common/job-benefit/
https://rdapi.aayulogic.io/api/v1/common/job-benefit/stats/
https://rdapi.aayulogic.io/api/v1/common/job-benefit/{id}/
https://rdapi.aayulogic.io/api/v1/common/job-categories/
https://rdapi.aayulogic.io/api/v1/common/job-categories/{id}/
https://rdapi.aayulogic.io/api/v1/common/languages/
https://rdapi.aayulogic.io/api/v1/common/languages/stats/
https://rdapi.aayulogic.io/api/v1/common/languages/{id}/
https://rdapi.aayulogic.io/api/v1/common/locations/
https://rdapi.aayulogic.io/api/v1/common/locations/stats/
https://rdapi.aayulogic.io/api/v1/common/locations/{id}/
https://rdapi.aayulogic.io/api/v1/common/org-document-categories/
https://rdapi.aayulogic.io/api/v1/common/org-document-categories/{id}/
https://rdapi.aayulogic.io/api/v1/common/other-advantage-factors/
https://rdapi.aayulogic.io/api/v1/common/other-advantage-factors/stats/
https://rdapi.aayulogic.io/api/v1/common/other-advantage-factors/{id}/
https://rdapi.aayulogic.io/api/v1/common/personal-qualities/
https://rdapi.aayulogic.io/api/v1/common/personal-qualities/stats/
https://rdapi.aayulogic.io/api/v1/common/personal-qualities/{id}/
https://rdapi.aayulogic.io/api/v1/common/province/
https://rdapi.aayulogic.io/api/v1/common/province/{id}/
https://rdapi.aayulogic.io/api/v1/common/religion/
https://rdapi.aayulogic.io/api/v1/common/religion/{id}/
https://rdapi.aayulogic.io/api/v1/common/required-knowledge/
https://rdapi.aayulogic.io/api/v1/common/required-knowledge/stats/
https://rdapi.aayulogic.io/api/v1/common/required-knowledge/{id}/
https://rdapi.aayulogic.io/api/v1/common/skills/
https://rdapi.aayulogic.io/api/v1/common/skills/stats/
https://rdapi.aayulogic.io/api/v1/common/skills/{id}/
https://rdapi.aayulogic.io/api/v1/common/survey-cities/
https://rdapi.aayulogic.io/api/v1/common/trainings/
https://rdapi.aayulogic.io/api/v1/common/trainings/stats/
https://rdapi.aayulogic.io/api/v1/common/trainings/{id}/
https://rdapi.aayulogic.io/api/v1/common/work-standards/
https://rdapi.aayulogic.io/api/v1/common/work-standards/stats/
https://rdapi.aayulogic.io/api/v1/common/work-standards/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/covid-user/
https://rdapi.aayulogic.io/api/v1/control-panel/covid-user/stats/
https://rdapi.aayulogic.io/api/v1/control-panel/covid-user/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/designations/
https://rdapi.aayulogic.io/api/v1/control-panel/designations/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/employers/
https://rdapi.aayulogic.io/api/v1/control-panel/employers/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/jobseekers/
https://rdapi.aayulogic.io/api/v1/control-panel/jobseekers/advance-search/
https://rdapi.aayulogic.io/api/v1/control-panel/jobseekers/stats/
https://rdapi.aayulogic.io/api/v1/control-panel/jobseekers/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/managers/
https://rdapi.aayulogic.io/api/v1/control-panel/organization/
https://rdapi.aayulogic.io/api/v1/control-panel/organization/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/permissions/
https://rdapi.aayulogic.io/api/v1/control-panel/templates/
https://rdapi.aayulogic.io/api/v1/control-panel/templates/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/user/
https://rdapi.aayulogic.io/api/v1/control-panel/user/registered/
https://rdapi.aayulogic.io/api/v1/control-panel/user/{id}/
https://rdapi.aayulogic.io/api/v1/control-panel/user/{id}/block/
https://rdapi.aayulogic.io/api/v1/control-panel/user/{id}/unblock/
https://rdapi.aayulogic.io/api/v1/crm/employers/
https://rdapi.aayulogic.io/api/v1/crm/employers/{id}/
https://rdapi.aayulogic.io/api/v1/crm/organizations/
https://rdapi.aayulogic.io/api/v1/crm/organizations/{id}/
https://rdapi.aayulogic.io/api/v1/employers/
https://rdapi.aayulogic.io/api/v1/employers/organization/
https://rdapi.aayulogic.io/api/v1/employers/organization/{id}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/jobseeker-shortlist/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/liked-jobseekers/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-basic-info/{slug}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-contacts/{slug}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-create/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-documents/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-documents/{id}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-overview/{slug}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-services/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-services/{id}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-social-accounts/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization-social-accounts/{id}/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization/{organization_slug}/contact-person/
https://rdapi.aayulogic.io/api/v1/employers/{employer_id}/organization/{organization_slug}/contact-person/{id}/
https://rdapi.aayulogic.io/api/v1/employers/{id}/
https://rdapi.aayulogic.io/api/v1/job/
https://rdapi.aayulogic.io/api/v1/job/basic-info-new/
https://rdapi.aayulogic.io/api/v1/job/basic-info/
https://rdapi.aayulogic.io/api/v1/job/home-page-jobs/
https://rdapi.aayulogic.io/api/v1/job/job-tag/
https://rdapi.aayulogic.io/api/v1/job/job-tag/{id}/
https://rdapi.aayulogic.io/api/v1/job/jobs-by-categories/
https://rdapi.aayulogic.io/api/v1/job/jobs-by-industries/
https://rdapi.aayulogic.io/api/v1/job/jobs-by-locations/
https://rdapi.aayulogic.io/api/v1/job/jobs-by-skills/
https://rdapi.aayulogic.io/api/v1/job/jobs-by-tags/
https://rdapi.aayulogic.io/api/v1/job/jobservice/
https://rdapi.aayulogic.io/api/v1/job/jobservice/{id}/
https://rdapi.aayulogic.io/api/v1/job/jobsource/
https://rdapi.aayulogic.io/api/v1/job/jobsource/{id}/
https://rdapi.aayulogic.io/api/v1/job/price-settings/
https://rdapi.aayulogic.io/api/v1/job/price-settings/final-price/
https://rdapi.aayulogic.io/api/v1/job/price-settings/{id}/
https://rdapi.aayulogic.io/api/v1/job/recommendations/
https://rdapi.aayulogic.io/api/v1/job/recommendations/{id}/
https://rdapi.aayulogic.io/api/v1/job/search/
https://rdapi.aayulogic.io/api/v1/job/search/count/
https://rdapi.aayulogic.io/api/v1/job/search/{slug}/
https://rdapi.aayulogic.io/api/v1/job/search/{slug}/like/
https://rdapi.aayulogic.io/api/v1/job/search/{slug}/unlike/
https://rdapi.aayulogic.io/api/v1/job/serviceprice/
https://rdapi.aayulogic.io/api/v1/job/serviceprice/{id}/
https://rdapi.aayulogic.io/api/v1/job/stats/
https://rdapi.aayulogic.io/api/v1/job/templates/
https://rdapi.aayulogic.io/api/v1/job/templates/{id}/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/applications/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/applications/{id}/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/applications/{id}/answers/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/applications/{id}/hold/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/applications/{id}/unhold/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/apply/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/apply/jobseeker-preference/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/questions/
https://rdapi.aayulogic.io/api/v1/job/{job_slug}/questions/{id}/
https://rdapi.aayulogic.io/api/v1/job/{slug}/
https://rdapi.aayulogic.io/api/v1/job/{slug}/additional-info-new/
https://rdapi.aayulogic.io/api/v1/job/{slug}/additional-info/
https://rdapi.aayulogic.io/api/v1/job/{slug}/basic-info-new/
https://rdapi.aayulogic.io/api/v1/job/{slug}/basic-info/
https://rdapi.aayulogic.io/api/v1/job/{slug}/clone/
https://rdapi.aayulogic.io/api/v1/job/{slug}/final-step/
https://rdapi.aayulogic.io/api/v1/job/{slug}/job-specification-new/
https://rdapi.aayulogic.io/api/v1/job/{slug}/publish/
https://rdapi.aayulogic.io/api/v1/job/{slug}/specification/
https://rdapi.aayulogic.io/api/v1/job/{slug}/status-change/
https://rdapi.aayulogic.io/api/v1/job/{slug}/update-tags/
https://rdapi.aayulogic.io/api/v1/jobseekers/
https://rdapi.aayulogic.io/api/v1/jobseekers/by-category/
https://rdapi.aayulogic.io/api/v1/jobseekers/by-location/
https://rdapi.aayulogic.io/api/v1/jobseekers/home-page-jobseekers/
https://rdapi.aayulogic.io/api/v1/jobseekers/search/
https://rdapi.aayulogic.io/api/v1/jobseekers/search/total/
https://rdapi.aayulogic.io/api/v1/jobseekers/search/{user__username}/
https://rdapi.aayulogic.io/api/v1/jobseekers/search/{user__username}/like/
https://rdapi.aayulogic.io/api/v1/jobseekers/search/{user__username}/unlike/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/applied-jobs/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/applied-jobs/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/contacts/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/contacts/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/cv/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/documents/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/documents/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/educations/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/educations/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/initial-form/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/languages/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/languages/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/liked-jobs/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/liked-jobs/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/other-info/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/overview/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/preference/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/profile-visits/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/profile-visits/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/references/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/references/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/social-accounts/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/social-accounts/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/trainings/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/trainings/{id}/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/work-experiences/
https://rdapi.aayulogic.io/api/v1/jobseekers/{jobseeker_id}/work-experiences/{id}/
https://rdapi.aayulogic.io/api/v1/sitemap/jobs/
https://rdapi.aayulogic.io/api/v1/sitemap/trainings/
https://rdapi.aayulogic.io/api/v1/survey/questions-set/
https://rdapi.aayulogic.io/api/v1/survey/questions-set/{id}/
https://rdapi.aayulogic.io/api/v1/survey/questions/
https://rdapi.aayulogic.io/api/v1/survey/questions/{id}/
https://rdapi.aayulogic.io/api/v1/survey/step-four/{id}/
https://rdapi.aayulogic.io/api/v1/survey/step-one/{id}/
https://rdapi.aayulogic.io/api/v1/survey/step-three/{id}/
https://rdapi.aayulogic.io/api/v1/survey/step-two/{id}/
https://rdapi.aayulogic.io/api/v1/survey/survey-user-detail/{id}/
https://rdapi.aayulogic.io/api/v1/survey/users-answers/
https://rdapi.aayulogic.io/api/v1/survey/users-answers/{id}/
https://rdapi.aayulogic.io/api/v1/training/
https://rdapi.aayulogic.io/api/v1/training/stats/
https://rdapi.aayulogic.io/api/v1/training/{slug}/
https://rdapi.aayulogic.io/api/v1/training/{slug}/send-mail/
https://rdapi.aayulogic.io/api/v1/users/
https://rdapi.aayulogic.io/api/v1/users/change-password/
https://rdapi.aayulogic.io/api/v1/users/covid-user-register/
https://rdapi.aayulogic.io/api/v1/users/employer-register/
https://rdapi.aayulogic.io/api/v1/users/jobseeker-register/
https://rdapi.aayulogic.io/api/v1/users/me/
https://rdapi.aayulogic.io/api/v1/users/me/complete-survey/
https://rdapi.aayulogic.io/api/v1/users/permissions/
https://rdapi.aayulogic.io/api/v1/users/set-password/
https://rdapi.aayulogic.io/api/v1/users/{id}/
https://rdapi.aayulogic.io/api/v1/users/{id}/answers/
https://rdapi.aayulogic.io/api/v1/users/{id}/reward-points/
/versions/
